[NEX-12] Edit Product
stodorichkov/SAP-Nexus-Server pull request #47
Opened 2024-04-16 16:47 UTC by TotLiBatLi

2024-04-16 18:27 UTC, stodorichkov requested changes

2024-04-16 18:27 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/controller/AdminController.java
>  }
Add one more patch for change product campaignDsicount. If campaign is active change disccount too.

2024-04-16 18:27 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/service/EditProductServiceImpl.java
> +        final var imageUrl = this.fileService.upload(productRequest.image());
add one empty line

2024-04-16 18:27 UTC, stodorichkov commented on nexus/src/test/java/com/example/nexus/service/EditProductServiceImplTest.java
> +
remove empty line

2024-04-16 18:27 UTC, stodorichkov commented on nexus/src/test/java/com/example/nexus/service/EditProductServiceImplTest.java
> +
remove empty line

2024-04-16 18:27 UTC, stodorichkov commented on nexus/src/test/java/com/example/nexus/service/EditProductServiceImplTest.java
> +
remove empty line

2024-04-16 18:27 UTC, stodorichkov commented on nexus/src/test/java/com/example/nexus/service/EditProductServiceImplTest.java
> +
add test if product not found

2024-04-16 18:27 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/model/payload/request/ProductRequest.java
> +        Integer discount,
Add @RequestParam(required = false) because when create product we dont need to set discount

2024-04-17 19:17 UTC, stodorichkov requested changes

2024-04-17 19:17 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/controller/AdminController.java
> +    public ResponseEntity<?> editProductCampaignDiscount(@Valid @PathVariable Long productId, @PathVariable Integer discount) {
remove Valid. Also get discount as Request Body

2024-04-17 19:17 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/model/payload/request/ProductRequest.java
> +        @RequestParam
@RequestParam(required = false)

2024-04-17 19:17 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/service/EditProductServiceImpl.java
> +            throw new IllegalStateException(MessageConstants.PRODUCT_NOT_FOUND);
dont trow exception just set campaignDiscount

2024-04-18 10:55 UTC, stodorichkov requested changes

2024-04-18 10:55 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/service/EditProductService.java
> +public interface EditProductService {
Dont need a separate service use product service

2024-04-18 10:55 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/controller/AdminController.java
> +    public ResponseEntity<?> editProductCampaignDiscount(@PathVariable Long productId, @RequestBody Integer discount) {
Make a separate record for request and add validations

2024-04-18 11:07 UTC, stodorichkov requested changes

2024-04-18 11:07 UTC, stodorichkov commented on nexus/src/main/java/com/example/nexus/service/EditProductServiceImpl.java
> +        if (campaign != null && campaign.getIsActive()) {
if (campsign != null) {
 if(campaign.getIsActive) {
  // set product discount
 }
// set product campaign discount
}

2024-04-18 20:51 UTC, TotLiBatLi commented on nexus/src/main/java/com/example/nexus/controller/AdminController.java
> +
не го гледай тва

2024-04-18 22:26 UTC, stodorichkov approved these changes

2024-04-18 22:54 UTC, merged